export const employeeData = {
  forYear: 2023,
  forPeriodFrom: "0101",
  forPeriodTo: 1231,
  tin: 2415171900000,
  empName: "TORRES CHRISTINE DIANE ARINO",
  empRegisteredAddress: "B2 L34 PHASE 6 SMERSET LANCASTER NEW CITY, ",
  empLocalAddress: "",
  empForeignAddress: "",
  rdoCode: "124",
  empRegAddrZipCode: "",
  empLocAddrZipCode: "",
  presentEmpZipCode: "1635",
  dob: "10171983",
  contactNumber: "",
  statutoryMinWageRatePerDay: "",
  statutoryMinWageRatePerMonth: "",
  minWageEarner: true,
  prevEmployerName:"",
  prevEmpZipCode: "1223",
  presentEmployerTin: "0050395520000",
  prevEmployerTin: "",
  presentEmployerName: "ASCENTHR DEMO",
  presentEmployerRegAddr:
    "Unit 505, The Finance Center, 29th St., corner 15th Avenue",
  prevEmployerRegAddr: "",
  grossIncomePresentEmployer: "1442591.86",
  totalNonTaxableIcomePresentEmployer: "139980.35",
  taxableIncomePresentEmployer: "1302611.51",
  taxableCompIncomePrevEmployer: "0.00",
  grossTaxableCompIncome: "1302611.51",
  taxDue: "228152.88",
  amntTaxWithheldPresentEmployer: 228152.88,
  amntTaxWithheldPrevEmployer: "0.00",
  totalAmntTaxesAdjusted: "228152.88",
  taxCredit: "",
  totalTaxesWithheld: 228152.88,
  nonTaxableBasicSal: "0.00",
  holidayPayMWE: "0.00",
  overtimePayMWE: "0.00",
  nightShiftDiffMWE: "0.00",
  hazardPayMWE: "0.00",
  "13MonthPay": "90000.00",
  deMinimisBenefits: "14400.00",
  sssContributions: "35580.35",
  salariesOtherComp: "0.00",
  totalNonTaxableComp: 139980.35,
  taxableBasicSal: "1241121.53",
  representation: "0.00",
  transportation: "0.00",
  cola: "0.00",
  fixedHousingAllowance: "0.00",
  other44a: "",
  other44a1: "0.00",
  other44b: "",
  other44b1: "0.00",
  commission: "0.00",
  profitSharing: "0.00",
  directorFee: "0.00",
  taxable13MonthBenefits: "61489.98",
  suppHazardPay: "0.00",
  suppOvertimePay: "0.00",
  others51a: "",
  others51a1: "0.00",
  others51b: "",
  others51b1: "0.00",
  totalTaxableCompIncome: 1302611.51,
  secEmployer: true,
  mainEmployer: true,
  presentEmployerSign: "Angle Fatima",
  empSign: "TORRES CHRISTINE DIANE ARINO",
  presentEmployerSign1: "Angle Fatima",
  empSign1: "TORRES CHRISTINE DIANE ARINO",
  placeOfIssue: "",
  amntPaid: "",
  presentEmployerSignDate: "01312024",
  empSignDate: "",
  issuedDate: "",
  empValidId: "",
};


export const fieldMappings = {
  presentEmployerSignDate: [
    "presentEmployerSignDate1",
    "presentEmployerSignDate2",
    "presentEmployerSignDate3",
    "presentEmployerSignDate4",
    "presentEmployerSignDate5",
    "presentEmployerSignDate6",
    "presentEmployerSignDate7",
    "presentEmployerSignDate8",
  ],
  empSignDate: [
    "empSignDate1",
    "empSignDate2",
    "empSignDate3",
    "empSignDate4",
    "empSignDate5",
    "empSignDate6",
    "empSignDate7",
    "empSignDate8",
  ],
  issuedDate: [
    "issuedDate1",
    "issuedDate2",
    "issuedDate3",
    "issuedDate4",
    "issuedDate5",
    "issuedDate6",
    "issuedDate7",
    "issuedDate8",
  ],
  forYear: ["forYear1", "forYear2", "forYear3", "forYear4"],
  tin: [
    "tin1",
    "tin2",
    "tin3",
    "tin4",
    "tin5",
    "tin6",
    "tin7",
    "tin8",
    "tin9",
    "tin11",
    "tin12",
    "tin13",
    "tin14",
  ],
  rdoCode: ["rdoCode1", "rdoCode2", "rdoCode3"],
  empRegAddrZipCode: [
    "empRegAddrZipCode1",
    "empRegAddrZipCode2",
    "empRegAddrZipCode3",
    "empRegAddrZipCode4",
  ],
  empLocAddrZipCode: [
    "empLocAddrZipCode1",
    "empLocAddrZipCode2",
    "empLocAddrZipCode3",
    "empLocAddrZipCode4",
  ],
  dob: ["dob1", "dob2", "dob3", "dob4", "dob5", "dob6", "dob7", "dob8"],
  contactNumber: [
    "contactNum1",
    "contactNum2",
    "contactNumber3",
    "contactNumber4",
    "contactNumber5",
    "contactNumber6",
    "contactNumber7",
    "contactNumber8",
    "contactNumber9",
    "contactNumber10",
    "contactNumber11",
  ],
  presentEmployerTin: [
    "presentEmployerTin1",
    "presentEmployerTin2",
    "presentEmployerTin3",
    "presentEmployerTin4",
    "presentEmployerTin5",
    "presentEmployerTin6",
    "presentEmployerTin7",
    "presentEmployerTin8",
    "presentEmployerTin9",
    "presentEmployerTin11",
    "presentEmployerTin12",
    "presentEmployerTin13",
    "presentEmployerTin14",
  ],
  prevEmployerTin: [
    "prevEmployerTin1",
    "prevEmployerTin2",
    "prevEmployerTin3",
    "prevEmployerTin4",
    "prevEmployerTin5",
    "prevEmployerTin6",
    "prevEmployerTin7",
    "prevEmployerTin8",
    "prevEmployerTin9",
    "prevEmployerTin11",
    "prevEmployerTin12",
    "prevEmployerTin13",
    "prevEmployerTin14",
  ],
  forPeriodFrom: [
    "forPeriodFrom1",
    "forPeriodFrom2",
    "forPeriodFrom3",
    "forPeriodFrom4",
  ],
  forPeriodTo: ["forPeriodTo1", "forPeriodTo2", "forPeriodTo3", "forPeriodTo4"],
  presentEmpZipCode: [
    "presentEmpZipCode1",
    "presentEmpZipCode2",
    "presentEmpZipCode3",
    "presentEmpZipCode4",
  ],
  prevEmpZipCode: [
    "prevEmpZipCode1",
    "prevEmpZipCode2",
    "prevEmpZipCode3",
    "prevEmpZipCode4",
  ],
};